/*
 * Autogenerated GraphQL Schema
 * https://www.gastbyjs.com/docs/reference/config-files/actions/#printTypeDefinitions
 */
const fs = require('fs');

exports.createSchemaCustomization = ({ actions }) => {
  fs.unlink('./schema.gql', (err) => {
    if (err) {
      console.info("Creating schema file for the first time! :D");
    }

    actions.printTypeDefinitions({});
  });
}